return {
	descriptions = {
		Tag = {
			tag_mp_sandbox_rare = {
				name = "Gambling Tag",
				text = {
					"{C:green}#1# in #2#{} chance",
					"Shop has a free",
					"{C:red}Rare Joker{}",
				},
			},
		},
		Joker = {
			j_broken = {
				name = "BROKEN",
				text = {
					"This card is either broken or",
					"not implemented in the current",
					"version of a mod you are using.",
				},
			},
			j_mp_defensive_joker = {
				name = "Defensive Joker",
				text = {
					"{C:chips}+#1#{} Chips for every {C:red,E:1}life{}",
					"less than your {X:purple,C:white}Nemesis{}",
					"{C:inactive}(Currently {C:chips}+#2#{C:inactive} Chips)",
					"{C:inactive}(Stake-dependent)",
				},
			},
			j_mp_skip_off = {
				name = "Skip-Off",
				text = {
					"{C:blue}+#1#{} Hands and {C:red}+#2#{} Discards",
					"per additional {C:attention}Blind{} skipped",
					"compared to your {X:purple,C:white}Nemesis{}",
					"{C:inactive}(Currently {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive}, #5#)",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Let's Go Gambling",
				text = {
					"{C:green}#1# in #2#{} chance for",
					"{X:mult,C:white}X#3#{} Mult and {C:money}$#4#{}",
					"{C:green}#5# in #6#{} chance to give",
					"your {X:purple,C:white}Nemesis{} {C:money}$#7#{} in {C:attention}PvP Blind",
				},
			},
			j_mp_speedrun = {
				name = "SPEEDRUN",
				text = {
					"If you reach a {C:attention}PvP Blind",
					"before your {X:purple,C:white}Nemesis{},",
					"create a random {C:spectral}Spectral{} card",
					"{C:inactive}(Must have room)",
				},
			},
			j_mp_conjoined_joker = {
				name = "Conjoined Joker",
				text = {
					"While in a {C:attention}PvP Blind{}, gain",
					"{X:mult,C:white}X#1#{} Mult for every {C:blue}Hand{}",
					"your {X:purple,C:white}Nemesis{} has left",
					"{C:inactive}(Max {X:mult,C:white}X#2#{C:inactive} Mult, Currently {X:mult,C:white}X#3#{C:inactive} Mult)",
				},
			},
			j_mp_penny_pincher = {
				name = "Penny Pincher",
				text = {
					"At end of round, earn {C:money}$#1#{} for",
					"every {C:money}$#2#{} your {X:purple,C:white}Nemesis{} spent",
					"in corresponding shop {C:attention}last ante{}",
				},
			},
			j_mp_taxes = {
				name = "Taxes",
				text = {
					"Gains {C:mult}+#1#{} Mult for every card your",
					"{X:purple,C:white}Nemesis{} {C:attention}sold{} since last {C:attention}PvP Blind{},",
					"updates when {C:attention}PvP Blind{} is selected",
					"{C:inactive}(Currently {C:mult}+#2#{C:inactive} Mult)",
				},
			},
			j_mp_magnet = {
				name = "Magnet",
				text = {
					"After {C:attention}#1#{} rounds,",
					"sell this card to {C:attention}Copy{}",
					"your {X:purple,C:white}Nemesis'{} highest ",
					"sell cost {C:attention}Joker{}",
					"{C:inactive}(Currently {C:attention}#2#{C:inactive}/#3# rounds)",
				},
			},
			j_mp_pizza = {
				name = "Pizza",
				text = {
					"At the end of the next {C:attention}PvP Blind{},",
					"consume this Joker and grant",
					"{C:red}+#1#{} discards to you and",
					"{C:red}+#2#{} discards to your {X:purple,C:white}Nemesis{} for the ante",
				},
			},
			j_mp_pacifist = {
				name = "Pacifist",
				text = {
					"{X:mult,C:white}X#1#{} Mult while",
					"not in a {C:attention}PvP Blind{}",
				},
			},
			j_hanging_chad_mp_standard = {
				name = "Hanging Chad",
				text = {
					"Retrigger {C:attention}first{} and {C:attention}second{}",
					"played card used in scoring",
					"{C:attention}#1#{} additional time",
				},
			},
			j_mp_cloud_9 = {
				name = "Cloud 9",
				text = {
					"Earn {C:money}$1{} for each {C:attention}9{} in deck",
					"(max {C:money}$4{}), then {C:money}$#1#{} for each",
					"additional {C:attention}9{} at end of round",
					"{C:inactive}(Currently {C:money}$#2#{}{C:inactive})",
				},
			},
			j_mp_bloodstone = {
				name = "Bloodstone",
				text = {
					"{C:green}#1# in #2#{} chance for",
					"played cards with",
					"{C:hearts}Heart{} suit to give",
					"{X:mult,C:white} X#3# {} Mult when scored",
					"{C:inactive}(Includes experimental variance){}",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Asteroid",
				text = {
					"Remove #1# level from",
					"your {X:purple,C:white}Nemesis'{}",
					"highest level {C:legendary,E:1}poker hand{}",
					"at start of {C:attention}PvP Blind{}",
				},
			},
		},
		Blind = {
			bl_mp_nemesis = {
				name = "Your Nemesis",
				text = {
					"Face another player,",
					"most chips wins",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "Phantom",
				text = {
					"{C:attention}Eternal{} and {C:dark_edition}Negative{}",
					"Created and destroyed by your {X:purple,C:white}Nemesis{}",
				},
			},
		},
		Enhanced = {
			m_mp_glass = {
				name = "Glass Card",
				text = {
					"{X:mult,C:white} X#1# {} Mult",
					"{C:green}#2# in #3#{} chance to",
					"destroy card",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Nemesis",
				text = {
					"{X:purple,C:white}#1#{}",
					"Your one and only Nemesis",
				},
			},
		},
	},
	misc = {
		labels = {
			mp_phantom = "Phantom",
		},
		challenge_names = {
			c_mp_standard = "Standard",
			c_mp_sandbox = "Sandbox",
			c_mp_badlatro = "Badlatro",
			c_mp_tournament = "Tournament",
			c_mp_weekly = "Weekly",
			c_mp_vanilla = "Vanilla",
		},
		dictionary = {
			b_singleplayer = "Singleplayer",
			b_join_lobby = "Join Lobby",
			b_return_lobby = "Return to Lobby",
			b_reconnect = "Reconnect",
			b_create_lobby = "Create Lobby",
			b_start_lobby = "Start Lobby",
			b_ready = "Ready",
			b_unready = "Unready",
			b_leave_lobby = "Leave Lobby",
			b_mp_discord = "Balatro Multiplayer Discord Server",
			b_start = "START",
			b_wait_for_host_start = { "WAITING FOR", "HOST TO START" },
			b_wait_for_players = { "WAITING FOR", "PLAYERS" },
			b_wait_for_guest_ready = { "WAITING FOR", "GUEST TO READY UP" },
			b_lobby_options = "LOBBY OPTIONS",
			b_copy_clipboard = "Copy to clipboard",
			b_view_code = "VIEW CODE",
			b_copy_code = "COPY CODE",
			b_leave = "LEAVE",
			b_opts_cb_money = "Give comeback $ on life loss",
			b_opts_no_gold_on_loss = "Don't get blind rewards on round loss",
			b_opts_death_on_loss = "Lose a life on non-PvP round loss",
			b_opts_start_antes = "Starting Antes",
			b_opts_diff_seeds = "Players have different seeds",
			b_opts_lives = "Lives",
			b_opts_multiplayer_jokers = "Enable Multiplayer Cards",
			b_opts_player_diff_deck = "Players have different decks",
			b_opts_normal_bosses = "Enable Boss Blind effects",
			b_opts_timer = "Enable Timer",
			b_reset = "Reset",
			b_set_custom_seed = "Set Custom Seed",
			b_mp_kofi_button = "Supporting me on Ko-fi",
			b_unstuck = "Unstuck",
			b_unstuck_blind = "Stuck Outside PvP",
			b_misprint_display = "Display the next card in the deck",
			b_players = "Players",
			b_lobby_info = "Lobby Info",
			b_continue_singleplayer = "Continue in Singleplayer",
			b_the_order_integration = "Enable The Order Integration",
			b_view_nemesis_deck = "View Decks",
			b_toggle_jokers = "Toggle Jokers",
			b_skip_tutorial = "Skip Tutorial",
			k_values_are_modifiable = "* Values are modifiable",
			k_rulesets = "Rulesets",
			k_gamemodes = "Gamemodes",
			k_competitive = "Competitive",
			k_standard = "Standard",
			k_other = "Other",
			k_battle = "Battle",
			k_challenge = "Challenge",
			k_info = "Info",
			k_continue_singleplayer_tooltip = "This will overwrite your current singleplayer run",
			k_enemy_score = "Current Enemy score",
			k_enemy_hands = "Enemy hands left: ",
			k_coming_soon = "Coming Soon!",
			k_wait_enemy = "Waiting for enemy to finish...",
			k_wait_enemy_reach_this_blind = "Waiting for enemy to reach this blind...",
			k_lives = "Lives",
			k_lost_life = "Lost a life",
			k_total_lives_lost = " Total Lives Lost ($4 each)",
			k_attrition_name = "Attrition",
			k_enter_lobby_code = "Enter Lobby Code",
			k_paste = "Paste From Clipboard",
			k_username = "Username:",
			k_enter_username = "Enter username",
			k_join_discord = "Join the ",
			k_discord_msg = "You can report any bugs and find players to play there",
			k_enter_to_save = "Press enter to save",
			k_in_lobby = "In the lobby",
			k_connected = "Connected to Service",
			k_warn_service = "WARN: Cannot Find Multiplayer Service",
			k_set_name = "Set your username in the main menu! (Mods > Multiplayer > Config)",
			k_mod_hash_warning = "Players have different mods or mod versions! This can cause problems!",
			k_steamodded_warning = "Players have different versions of Steamodded installed. This may cause the seeds to differ.",
			k_warning_unlock_profile = "The profile you are playing on is not fully unlocked. If this is a ranked/tournament game, please create a new profile and hit unlock all in the profile settings",
			k_warning_nemesis_unlock = "Your opponent is playing on a profile that is not fully unlocked. Please instruct them to create a new profile and hit unlock all in the profile settings",
			k_warning_no_order = "One player has The Order integration enabled while the other does not. This will cause the seeds to differ.",
			k_warning_cheating1 = "If you are seeing this, your opponent may be cheating.",
			k_warning_cheating2 = "If this is a ranked game, please send the message '%s' and then open a support ticket in #support",
			k_message1 = "Hold on, my mom made pizza pops",
			k_message2 = "One sec, i gotta grab my slow cooker pork roast",
			k_message3 = "One moment, getting a call from my mom",
			k_message4 = "Brb, my cat is on fire",
			k_message5 = "Wait, I think I left the stove on",
			k_message6 = "Hold up, my pet rock just ran away",
			k_message7 = "One sec, my plants are asking for water",
			k_message8 = "Brb, my socks are plotting against me",
			k_message9 = "Sorry, my WiFi is having an existential crisis",
			k_lobby_options = "Lobby Options",
			k_connect_player = "Connected Players:",
			k_opts_only_host = "Only the Lobby Host can change these options",
			k_opts_gm = "Gamemode Modifiers",
			k_opts_pvp_start_round = "PVP Starts at Ante",
			k_opts_pvp_timer = "Timer",
			k_opts_showdown_starting_antes = "Showdown Starts at Ante",
			k_opts_pvp_timer_increment = "Timer Increment",
			k_opts_pvp_countdown_seconds = "PvP Countdown Seconds",
			k_bl_life = "Life",
			k_bl_or = "or",
			k_bl_death = "Death",
			k_bl_mostchips = "Most chips wins",
			k_current_seed = "Current seed: ",
			k_random = "Random",
			k_standard = "Standard",
			k_standard_description = "The standard ruleset, includes Multiplayer cards and changes to the base game to fit the Multiplayer meta.",
			k_sandbox = "Steph's Sandbox",
			k_sandbox_description = "Like normal mode but someone gave the cards coffee and they're feeling chatty.",
			k_vanilla = "Vanilla",
			k_vanilla_description = "The vanilla ruleset, no Multiplayer cards, no modifications to base game content. This ruleset includes Multiplayer features like the timer",
			k_blitz = "Blitz",
			k_blitz_description = "The blitz ruleset, includes Multiplayer cards and changes to the base game to fit the Multiplayer meta. This ruleset includes cards and features that encourage fast play and using time as a resource.",
			k_traditional = "Traditional",
			k_traditional_description = "The traditional ruleset, includes Multiplayer cards and changes to the base game to fit the Multiplayer meta. This ruleset removes aspects of Multiplayer that use time as a resource, allowing you to play a more traditional and methodical game.",
			k_majorleague = "Major League",
			k_majorleague_description = "The major league ruleset, it follows the rules for Major League Balatro.",
			k_minorleague = "Minor League",
			k_minorleague_description = "The minor league ruleset, it follows the rules for Minor League Balatro.",
			k_ranked = "Ranked",
			k_ranked_description = "The ranked ruleset, this ruleset is the same as Blitz right now, but also forces the correct gamemode, lobby options, and The Order integration.",
			k_tournament = "Tournament",
			k_tournament_description = "The tournament ruleset, this is the same as the standard ruleset but doesn't allow changing the lobby options.",
			k_badlatro = "Badlatro",
			k_badlatro_description = "A weekly ruleset designed by @dr_monty_the_snek on the discord server that has been added to the mod permanently.",
			k_attrition = "Attrition",
			k_attrition_description = "After the first ante, every boss blind is a Nemesis blind. No time to prepare. This gamemode forces you to be battle-ready from the start.",
			k_showdown = "Showdown",
			k_showdown_description = "After the first 2 antes, every blind is a Nemesis blind. This gamemode gives you time to prepare before battle.",
			k_survival = "Survival",
			k_survival_description = "The player who beats the farthest blind wins. No Nemesis blinds. This gamemode is a test of your ability to gradually build-up to the highest scoring Vanilla hands.",
			k_weekly = "Weekly",
			k_weekly_description = "A special ruleset that changes weekly or bi-weekly. I guess you'll have to find out what it is! Currently: ",
			k_weekly_smallworld = "Small World",
			k_oops_ex = "Oops!",
			k_asteroids = "Asteroids",
			k_amount_short = "Amt.",
			k_filed_ex = "Filed!",
			k_timer = "Timer",
			k_mods_list = "Mods List",
			k_enemy_jokers = "Enemy Jokers",
			k_your_jokers = "Your Jokers",
			k_nemesis_deck = "Nemesis Deck",
			k_your_deck = "Your Deck",
			k_the_order_credit = "*Credit to @MathIsFun_",
			k_the_order_integration_desc = "This will patch card creation to not be ante-based and use a single pool for every type/rarity",
			k_requires_restart = "*Requires a restart to take effect",
			k_new_weekly_ruleset = "A new weekly ruleset is available!",
			k_currently_colon = "Currently: ",
			k_sync_locally = "Sync locally (Restarts game)",
			k_bans = "Bans",
			k_reworks = "Reworks",
			k_ruleset_disabled_the_order_required = "The Order is Required",
			k_ruleset_disabled_the_order_banned = "The Order is Banned",
			k_ruleset_not_found = "Unknown ruleset",
			k_tutorial_not_complete = "You must complete the tutorial before you can play Multiplayer",
			k_created_by = "Created by",
			k_major_contributors = "Major contributions by",
			ml_enemy_loc = { "Enemy", "location" },
			ml_mp_kofi_message = {
				"This mod and game server is",
				"developed and maintained by ",
				"one person, if",
				"you like it consider",
			},
			ml_lobby_info = { "Lobby", "Info" },
			loc_ready = "Ready for PvP",
			loc_selecting = "Selecting a Blind",
			loc_shop = "Shopping",
			loc_playing = "Playing ",
		},
		v_dictionary = {
			a_mp_art = { "Art: #1#" },
			a_mp_code = { "Code: #1#" },
			a_mp_idea = { "Idea: #1#" },
			a_mp_skips_ahead = { "#1# Skips Ahead" },
			a_mp_skips_behind = { "#1# Skips Behind" },
			a_mp_skips_tied = { "Tied" },
			k_banned_objs = "Banned #1#",
			k_no_banned_objs = "No Banned #1#",
			k_reworked_objs = "Reworked #1#",
			k_no_reworked_objs = "No Reworked #1#",
			k_ruleset_disabled_smods_version = "SMODS Version #1# Required",
			k_failed_to_join_lobby = "Failed to join lobby: #1#",
			k_ante_number = "Ante #1#",
			k_ante_range = "Ante #1#-#2#",
			k_ante_min = "Ante #1#+",
		},
		v_text = {
			ch_c_hanging_chad_rework = { "{C:attention}Hanging Chad{} is {C:dark_edition}reworked" },
			ch_c_glass_cards_rework = { "{C:attention}Glass Cards{} are {C:dark_edition}reworked" },
		},
		challenge_names = {
			c_mp_misprint_deck = "Misprint Deck",
			c_mp_legendaries = "Legendaries",
			c_mp_psychosis = "Psychosis",
			c_mp_scratch = "From Scratch",
			c_mp_twin_towers = "Twin Towers",
			c_mp_in_the_red = "In the Red",
			c_mp_paper_money = "Paper Money",
			c_mp_high_hand = "High Hand",
			c_mp_chore_list = "Chore List",
			c_mp_oops_all_jokers = "Oops! All Jokers",
			c_mp_divination = "Divination",
			c_mp_skip_off = "Skip-Off",
			c_mp_lets_go_gambling = "Let's Go Gambling",
			c_mp_speed = "Speed",
		},
	},
}
