-- Localization by @themike_71
-- Corrections and further updates by ElTioRata
return {
	descriptions = {
		Joker = {
			j_broken = {
				name = "ROTA",
				text = {
					"Esta carta está rota o",
					"no se implementó en la",
					"versión actual del mod.",
				},
			},
			j_mp_defensive_joker = {
				name = "Comodín defensivo",
				text = {
					"{C:chips}+#1#{} fichas por cada {C:red,E:1}vida{}",
					"menos que tu {X:purple,C:white}némesis{}",
					"{C:inactive}(Actualmente {C:chips}+#2#{C:inactive} fichas)",
				},
			},
			j_mp_skip_off = {
				name = "Avioncito",
				text = {
					"{C:blue}+#1#{} manos y {C:red}+#2#{} descartes",
					"por {C:attention}ciega{} adicional omitida",
					"en comparación con tu {X:purple,C:white}némesis{}",
					"{C:inactive}(Actualmente {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive}, #5#)",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Let's Go Gambling",
				text = {
					"{C:green}#1# en #2#{} posibilidades para",
					"{X:mult,C:white}X#3#{} multi y {C:money}$#4#{}",
					"{C:green}#5# en #6#{} posibilidades para darle",
					"{C:money}$#7# a tu {X:purple,C:white}némesis{}",
				},
			},
			j_mp_speedrun = {
				name = "Carrera de velocidad",
				text = {
					"Si alcanzas una {C:attention}ciega JcJ",
					"antes que tu {X:purple,C:white}némesis{},",
					"crea una carta {C:spectral}espectral{} al azar",
					"{C:inactive}(debe haber espacio)",
				},
			},
			j_mp_conjoined_joker = {
				name = "Comodín unido",
				text = {
					"Mientras estés en una {C:attention}ciega JcJ{}, gana",
					"{X:mult,C:white}X#1#{} multi por cada {C:blue}mano{}",
					"que tu {X:purple,C:white}némesis{} haya dejado",
					"{C:inactive}(Máx {X:mult,C:white}X#2#{C:inactive} multi, Actualmente {X:mult,C:white}X#3#{C:inactive} multi)",
				},
			},
			j_mp_penny_pincher = {
				name = "Ahorrativo",
				text = {
					"Cuando alcances la tienda, gana",
					"{C:money}$#1#{} por cada {C:money}$#2#{}",
					"que tu {X:purple,C:white}némesis{} haya gastado previamente",
				},
			},
			j_mp_taxes = {
				name = "Impuestos",
				text = {
					"Cuando tu {X:purple,C:white}némesis'{} vende",
					"una carta gana {C:mult}+#1#{} multi",
					"{C:inactive}(Actualmente {C:mult}+#2#{C:inactive} multi)",
				},
			},
			j_mp_magnet = {
				name = "Imán",
				text = {
					"Después de {C:attention}#1#{} rondas,",
					"vende esta carta para {C:attention}copiar{}",
					"el {C:attention}comodín{} más caro de tu ",
					"{X:purple,C:white}némesis'{}",
					"{C:inactive}(Actualmente {C:attention}#2#{C:inactive}/#3# rondas)",
					"{C:inactive,s:0.8}(No copia el estado del comodín)",
				},
			},
			j_mp_pizza = {
				name = "Pizza",
				text = {
					"{C:red}+#1#{} descartes para todos los jugadores",
					"{C:red}-#2#{} descartes cuando cualquier jugador",
					"selecciona una ciega",
					"Se desgasta cuando tu {X:purple,C:white}némesis{} omite",
				},
			},
			j_mp_pacifist = {
				name = "Pacifista",
				text = {
					"{X:mult,C:white}X#1#{} multi cuando",
					"no estás en una {C:attention}ciega JcJ{}",
				},
			},
			j_mp_hanging_chad = {
				name = "Papel perforado",
				text = {
					"Reactiva {C:attention}primera{} y {C:attention}segunda{}",
					"carta jugada que se usó para anotar",
					"{C:attention}#1#{} vez adicional",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Asteroide",
				text = {
					"Disminuye #1# nivel de la",
					"{C:legendary,E:1}mano de póker{}",
					"con el nivel más alto",
					"de tu {X:purple,C:white}némesis{}",
				},
			},
		},
		Blind = {
			bl_mp_nemesis = {
				name = "Tu némesis",
				text = {
					"Enfréntate a otro jugador,",
					"quien tenga más fichas gana",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "Fantasma",
				text = {
					"{C:attention}Eterno{} y {C:dark_edition}negativo{}",
					"Creado y destruido por tu {X:purple,C:white}némesis{}",
				},
			},
		},
		Enhanced = {
			m_mp_glass = {
				name = "Carta de vidrio",
				text = {
					"{X:mult,C:white} X#1# {} multi",
					"{C:green}#2# en #3#{} posibilidades",
					"de que la carta se destruya",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Némesis",
				text = {
					"{X:purple,C:white}#1#{}",
					"Tu único e inigualable némesis",
				},
			},
		},
	},
	misc = {
		labels = {
			mp_phantom = "Fantasma",
		},
		challenge_names = {
			c_mp_standard = "Estándar",
			c_mp_badlatro = "Badlatro",
			c_mp_tournament = "Torneo",
			c_mp_weekly = "Semanal",
			c_mp_vanilla = "Vainilla",
		},
		dictionary = {
			b_singleplayer = "Un jugador",
			b_join_lobby = "Unirse a sala",
			b_return_lobby = "Volver a sala",
			b_reconnect = "Reconectar",
			b_create_lobby = "Crear sala",
			b_start_lobby = "Iniciar sala",
			b_ready = "Prepararse",
			b_unready = "Desprepararse",
			b_leave_lobby = "Dejar sala",
			b_mp_discord = "Servidor de Discord del multijugador de Balatro",
			b_start = "INICIAR",
			b_wait_for_host_start = { "ESPERANDO AL", "ANFITRIÓN PARA INICIAR" },
			b_wait_for_players = { "ESPERANDO", "JUGADORES" },
			b_lobby_options = "OPCIONES DE SALA",
			b_copy_clipboard = "Copiar al portapapeles",
			b_view_code = "VER CÓDIGO",
			b_leave = "DEJAR",
			b_opts_cb_money = "Recibe $ al perder una vida",
			b_opts_no_gold_on_loss = "No obtener recompensas de ciegas al perder la ronda",
			b_opts_death_on_loss = "Pierde una vida al perder en rondas no-JcJ",
			b_opts_start_antes = "Apuestas iniciales",
			b_opts_diff_seeds = "Los jugadores están en semillas diferentes",
			b_opts_lives = "Vidas",
			b_opts_multiplayer_jokers = "Habilitar cartas multijugador",
			b_opts_player_diff_deck = "Los jugadores tienen barajas diferentes",
			b_reset = "Reiniciar",
			b_set_custom_seed = "Ingresar semilla personalizada",
			b_mp_kofi_button = "Apoyar en Ko-fi",
			b_unstuck = "Desatascar",
			b_unstuck_arcana = "Atascado en paquete potenciador",
			b_unstuck_blind = "Atascado fuera de JcJ",
			b_misprint_display = "Muestra la siguiente carta en la baraja",
			b_players = "Jugadores",
			b_continue_singleplayer = "Continuar partida individual",
			k_enemy_score = "Puntuación del enemigo",
			k_enemy_hands = "Manos del enemigo: ",
			k_coming_soon = "¡Muy pronto!",
			k_wait_enemy = "Esperando que termine el enemigo...",
			k_lives = "Vidas",
			k_lost_life = "Perdiste una vida",
			k_total_lives_lost = " Total de vidas perdidas ($4 c/u)",
			k_attrition_name = "Atrición",
			k_enter_lobby_code = "Ingresar código de sala",
			k_paste = "Pegar desde portapapeles",
			k_username = "Nombre de usuario:",
			k_enter_username = "Ingresar nombre de usuario",
			k_join_discord = "Unirse al ",
			k_discord_msg = "Puedes reportar cualquier error y encontrar jugadores allí",
			k_enter_to_save = "Oprime ENTER para guardar",
			k_in_lobby = "En la sala",
			k_connected = "Conectado al servicio",
			k_warn_service = "AVISO: No se puede encontrar el servicio multijugador",
			k_set_name = "¡Establece tu nombre de usuario en el menú principal! (Mods > Multijugador > Configuración)",
			k_mod_hash_warning = "¡Los jugadores tienen diferentes mods o versiones! ¡Esto puede causar problemas!",
			k_lobby_options = "Opciones de sala",
			k_connect_player = "Jugadores conectados:",
			k_opts_only_host = "Solo el anfitrión de la sala puede cambiar estas opciones",
			k_opts_gm = "Modificadores",
			k_bl_life = "VIDA",
			k_bl_or = "o",
			k_bl_death = "MUERTE",
			k_current_seed = "Semilla actual: ",
			k_random = "Al azar",
			k_standard = "Estándar",
			k_standard_description = "El conjunto de reglas estándar, incluye cartas multijugador y cambios al juego base para ajustarse al meta multijugador.",
			k_vanilla = "Vainilla",
			k_vanilla_description = "El conjunto de reglas vainilla, sin cartas multijugador, sin modificaciones al contenido del juego base.",
			k_weekly = "Semanal",
			k_weekly_description = "Un conjunto de reglas especial que cambia semanal o quincenalmente. ¡Supongo que tendrás que jugarlo para averiguar de qué trata! Actualmente: ",
			k_tournament = "Torneo",
			k_tournament_description = "El conjunto de reglas de torneo, es igual que el conjunto de reglas estándar pero no permite cambiar las opciones de sala.",
			k_badlatro = "Badlatro",
			k_badlatro_description = "Un conjunto de reglas semanal diseñado por @dr_monty_the_snek en el servidor de Discord que se agregó de forma permanente al mod.",
			k_oops_ex = "¡Ups!",
			k_timer = "Temporizador",
			k_mods_list = "Lista de mods",
			k_enemy_jokers = "Comodínes enemigos",
			ml_enemy_loc = { "Enemigo", "ubicación" },
			ml_mp_kofi_message = {
				"Este mod y servidor de juego está",
				"siendo desarrollado y mantenido",
				"por una persona, si te gusta",
				"considera",
			},
			loc_ready = "Listo para JcJ",
			loc_selecting = "Seleccionando ciega",
			loc_shop = "En la tienda",
			loc_playing = "Jugando ",
		},
		v_dictionary = {
			a_mp_art = { "Arte: #1#" },
			a_mp_code = { "Código: #1#" },
			a_mp_idea = { "Idea: #1#" },
			a_mp_skips_ahead = { "#1# omisiones por delante" },
			a_mp_skips_behind = { "#1# omisiones por detrás" },
			a_mp_skips_tied = { "empatadas" },
		},
		v_text = {
			ch_c_hanging_chad_rework = { "{C:attention}Papel perforado{} está {C:dark_edition}reelaborado" },
			ch_c_glass_cards_rework = { "{C:attention}Cartas de vidrio{} están {C:dark_edition}reelaboradas" },
		},
	},
}
