-- Traduzione creata da @ieatmilk(su discord) e conseguentemente aggiornata da @alexxyo(sempre su discord)
-- Localization by @ieatmilk and updated by @alexxyo
return {
	descriptions = {
		Joker = {
			j_broken = {
				name = "BROKEN",
				text = {
					"Questa carta non funziona o non è",
					"ancora stata implementata nella versione",
					"attuale di una mod che stai usando.",
				},
			},
			j_mp_defensive_joker = {
				name = "Jolly difensivo",
				text = {
					"Questo {C:attention}Jolly{} guadagna {C:chips}+#1#{} fiche",
					"per ogni {C:red,E:1}vita{} in meno della tua {X:purple,C:white}Nemesi",
					"{C:inactive}(Attualmente {C:chips}+#2#{C:inactive} fiche)",
				},
			},
			j_mp_skip_off = {
				name = "Campana",
				text = {
					"{C:blue}+#1#{} Mani e {C:red}+#2#{} Scarti",
					"per ogni {C:attention}buio{} saltato",
					"rispetto alla tua {X:purple,C:white}Nemesi{}",
					"{C:inactive}(Attualmente {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive})",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Let's go gambling!",
				text = {
					"{C:green}#1# probabilità su #2#{} di ricevere",
					"{X:mult,C:white}X#3#{} Mult e {C:money}$#4#",
					"{C:green}#5# probabilità su #6#{} di dare",
					"{C:money}$#7#{} alla tua {X:purple,C:white}Nemesi{} in un {C:attention}Buio PvP",
				},
			},
			j_mp_speedrun = {
				name = "SPEEDRUN",
				text = {
					"Se raggiungi un {C:attention}Buio PvP",
					"prima della tua {X:purple,C:white}Nemesi{}",
					"crea una carta {C:spectral}Spettrale{} a caso",
					"{C:inactive}(Serve spazio)",
				},
			},
			j_mp_conjoined_joker = {
				name = "Jolly congiunto",
				text = {
					"Se in un {C:attention}Buio PvP{}, ottiene",
					"{X:mult,C:white}X#1#{} Molt per ogni {C:blue}Mano{}",
					"rimanente alla tua {X:purple,C:white}Nemesi{}",
					"{C:inactive}(Max {X:mult,C:white}X#2#{C:inactive} Molt, Attualmente {X:mult,C:white}X#3#{C:inactive} Molt)",
				},
			},
			j_mp_penny_pincher = {
				name = "Spilorcio",
				text = {
					"Alla fine del round,",
					"guadagna {C:money}$#1#{} per ogni {C:money}$#2#{} spesi",
					"dalla tua {X:purple,C:white}Nemesi{} nell'ultimo negozio",
				},
			},
			j_mp_taxes = {
				name = "Tasse",
				text = {
					"Quando la tua {X:purple,C:white}Nemesi{} vende",
					"un {C:attention}Jolly{} guadagni {C:mult}+#1#{} Molt",
					"{C:inactive}(Attualmente {C:mult}+#2#{C:inactive} Molt)",
				},
			},
			j_mp_magnet = {
				name = "Magnete",
				text = {
					"Dopo {C:attention}#1#{} round,",
					"vendi questa carta per {C:attention}Copiare{}",
					"il {C:attention}Jolly{} più costoso",
					"della tua {X:purple,C:white}Nemesi",
					"{C:inactive}(Attualmente {C:attention}#2#{C:inactive}/#3# round)",
				},
			},
			j_mp_pizza = {
				name = "Pizza",
				text = {
					"{C:red}+#1#{} Scarti per ogni giocatore",
					"{C:red}-#2#{} Scarto quando un giocatore",
					"seleziona un {C:attention}buio.",
					"Viene {C:attention}mangiata{} quando la tua {X:purple,C:white}Nemesi{} salta",
				},
			},
			j_mp_pacifist = {
				name = "Pacifista",
				text = {
					"{X:mult,C:white}X#1#{} Molt",
					"fuori da un {C:attention}Buio PvP}",
				},
			},
			j_mp_hanging_chad = {
				name = "Scheda non valida",
				text = {
					"Riattiva la {C:attention}prima{} e la {C:attention}seconda",
					"carta giocata per ottenere punti",
					"{C:attention}#1#{} volta in più",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Asteroide",
				text = {
					"Rimuove #1# livello dalla",
					"{C:legendary,E:1}mano di poker{}",
					"di livello più alto",
					"della tua {X:purple,C:white}Nemesi{}",
				},
			},
		},
		Blind = {
			bl_mp_nemesis = {
				name = "La tua Nemesi",
				text = {
					"Sei contro un altro giocatore,",
					"chi fa più punti vince",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "Fantasma",
				text = {
					"{C:attention}Eterna{} e {C:dark_edition}Negativa{}",
					"Creata e distrutta dalla tua {X:purple,C:white}Nemesi{}",
				},
			},
		},
		Enhanced = {
			m_mp_glass = {
				name = "Carta di vetro",
				text = {
					"{X:mult,C:white} X#1#{} Molt",
					"{C:green}#2# probabilità su #3#{} di",
					"distruggere la carta",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Nemesi",
				text = {
					"{X:purple,C:white}#1#{}",
					"La tua sola e unica Nemesi",
				},
			},
		},
	},
	misc = {
		labels = {
			mp_phantom = "Phantom",
		},
		challenge_names = {
			c_mp_standard = "Standard",
			c_mp_badlatro = "Badlatro",
			c_mp_tournament = "Torneo",
			c_mp_weekly = "Settimanale",
			c_mp_vanilla = "Vanilla",
		},
		dictionary = {
			b_singleplayer = "Giocatore singolo",
			b_join_lobby = "Entra in una Lobby",
			b_return_lobby = "Ritorna alla Lobby",
			b_reconnect = "Riconnettiti",
			b_create_lobby = "Crea una Lobby",
			b_start_lobby = "Start Lobby",
			b_ready = "Pronto",
			b_unready = "Non pronto",
			b_leave_lobby = "Lascia Lobby",
			b_mp_discord = "Server Discord di Balatro Multiplayer",
			b_start = "START",
			b_wait_for_host_start = { "IN ATTESA", "DELL'HOST" },
			b_wait_for_players = { "IN ATTESA", "DI GIOCATORI" },
			b_lobby_options = "OPZIONI LOBBY",
			b_copy_clipboard = "Copia negli Appunti",
			b_view_code = "RIVELA IL CODICE",
			b_copy_code = "COPIA IL CODICE",
			b_leave = "ESCI",
			b_opts_cb_money = "Rimborsa 4$ per vita persa alla fine di ogni round",
			b_opts_no_gold_on_loss = "Non dare i $ del buio se perdi il round",
			b_opts_death_on_loss = "Perdi una vita in un round non PvP",
			b_opts_start_antes = "Anti iniziali",
			b_opts_diff_seeds = "I giocatori giocano in seed differenti",
			b_opts_lives = "Vite",
			b_opts_multiplayer_jokers = "Abilita carte multigiocatore",
			b_opts_player_diff_deck = "I giocatori hanno mazzi diversi",
			b_opts_normal_bosses = "Attiva l'effetto del buio Boss nei round PvP",
			b_reset = "Reset",
			b_set_custom_seed = "Imposta seed specifico",
			b_mp_kofi_button = "Supporta il creatore su Ko-fi",
			b_unstuck = "Premi se sei bloccato",
			b_unstuck_blind = "Bloccato in PvP esterno",
			b_misprint_display = "Mostra la prossima carta nel mazzo",
			b_players = "Giocatori",
			b_continue_singleplayer = "Continua in Giocatore singolo",
			b_the_order_integration = "Abilita il Jolly \"L'ordine\"",
			b_view_nemesis_deck = "Guarda mazzo",
			k_enemy_score = "Punteggio del Nemico",
			k_enemy_hands = "Mani rimanenti del Nemico: ",
			k_coming_soon = "In Arrivo!",
			k_wait_enemy = "Attendi che il nemico finisca...",
			k_wait_enemy_reach_this_blind = "Attendi che il nemico arrivi a questo buio...",
			k_lives = "Vite",
			k_lost_life = "Hai perso una vita",
			k_total_lives_lost = " Vite perse in totale ($4 ciascuna)",
			k_attrition_name = "Logoramento",
			k_enter_lobby_code = "Inserisci codice Lobby",
			k_paste = "Incolla dagli Appunti",
			k_username = "Nome utente:",
			k_enter_username = "Inserisci Nome utente",
			k_join_discord = "Unisciti al ",
			k_discord_msg = "Puoi segnalare bugs e trovare giocatori con la quale giocare lì",
			k_enter_to_save = "Premi Invio per salvare",
			k_in_lobby = "Nella Lobby",
			k_connected = "Connesso al Servizio",
			k_warn_service = "AVVISO: Impossibile Trovare Servizio Multigiocatore",
			k_set_name = "Imposta il tuo nome utente nel menu principale! (Mods > Multiplayer > Configurazione)",
			k_mod_hash_warning = "I giocatori hanno mod diverse o versioni di mod diverse! Questo può causare errori!",
			k_warning_unlock_profile = "ATTENZIONE! Stai giocando con un profilo non totalmente sbloccato!\nSe questa partita è classificata/torneo, per favore crea un nuovo profilo e premi \"Sblocca tutto\" nelle impostazioni del profilo",
			k_warning_nemesis_unlock = "ATTENZIONE! Il tuo avversario sta giocando con un profilo non totalmente sbloccato!\nPer favore se questa partita è classificata/torneo AVVISALO ADESSO!",
			k_warning_no_order = "Un giocatore ha l'opzione (Abilita il Jolly \"L'ordine\") abilitata, mentre l'altro no. Questo renderà i vostri seed diversi.",
			k_warning_cheating1 = "È probabile che il tuo avversario stia barando.",
			k_warning_cheating2 = "Se questa è una partita classificata per favore invia il messaggio \"%s\" in chat e poi apri un ticket in #support nel server discord",
			k_message1 = "Un momento, mia madre ha scolato la pasta",
			k_message2 = "Un secondo, devo andare a spegnere il ragù",
			k_message3 = "Un momento, mi sta chiamando mamma",
			k_message4 = "Torno subito, il mio gatto è a fuoco",
			k_message5 = "Aspetta, penso di aver lasciato acceso il forno",
			k_message6 = "Fermo! La mia roccia domestica è appena scappata",
			k_message7 = "Un secondo, le mie piante mi stanno chiedendo da bere",
			k_message8 = "Torno subito, i miei calzini stanno complottando contro di me",
			k_message9 = "Scusa, il mio WiFi sta avendo una crisi esistenziale",
			k_lobby_options = "Opzioni Lobby",
			k_connect_player = "Giocatori connessi:",
			k_opts_only_host = "Solo l'host della Lobby può cambiare queste opzioni",
			k_opts_gm = "Modificatori",
			k_opts_pvp_start_round = "Il PVP inizia all'ante",
			k_opts_pvp_timer = "Timer",
			k_opts_showdown_starting_antes = "La resa dei conti inizia all'ante",
			k_opts_pvp_timer_increment = "Incremento del timer",
			k_bl_life = "Vita",
			k_bl_or = "o",
			k_bl_death = "Morte",
			k_bl_mostchips = "chi fa più punti vince",
			k_current_seed = "Seed attuale: ",
			k_random = "Casuale",
			k_standard = "Standard",
			k_standard_description = "Le regole standard, includono le carte multigiocatore e cambiamenti a carte del gioco base per adattarle al meta del multigiocatore.",
			k_vanilla = "Vanilla",
			k_vanilla_description = "Le regole vanilla, nessuna carta multigiocatore, nessuna modifica al contenuto del gioco base",
			k_weekly = "Settimanale",
			k_weekly_description = "Delle regole speciali che cambiano ad intervallo settimanale o bisettimanale. Immagino dovrai scoprire cosa fanno! Attualmente: ",
			k_tournament = "Torneo",
			k_tournament_description = "Le regole del torneo, sono uguali alle regole standard ma non permettono di modificare le opzioni della Lobby.",
			k_badlatro = "Badlatro",
			k_badlatro_description = "Delle regole settimanali progettate da @dr_monty_the_snek nel server discord, che sono state aggiunte alla mod permanentemente.",
			k_attrition = "Logoramento",
			k_attrition_description = "Ogni buio Boss è un buio Nemesi. Non c'è tempo per prepararsi. Questa modalità ti forza ad essere pronto alla battaglia sin dall'inizio.",
			k_showdown = "Resa dei conti",
			k_showdown_description = "Dopo i primi 2 anti, ogni buio è un buio Nemesi. Questa modalità ti dà tempo di prepararti prima della battaglia.",
			k_survival = "Sopravvivenza",
			k_survival_description = "Il giocatore che batte il buio più lontano vince. Non ci sono bui nemesi. Questa modalità è un test per la tua abilità per aumentare gradualmente il record di punteggio con le mani vanilla.",
			k_oops_ex = "Aww, dang it!",
			k_timer = "Timer",
			k_mods_list = "Lista Mods",
			k_enemy_jokers = "Jolly nemici",
			k_nemesis_deck = "Mazzo della Nemesi",
			k_your_deck = "Il tuo mazzo",
			k_the_order_credit = "*Crediti a @MathIsFun_",
			k_the_order_integration_desc = "Questo modificherà la creazione delle carte in modo che non sia basata sull'ante ma utilizzi una singola riserva per ogni tipo/rarità",
			k_requires_restart = "*Richiede un riavvio per avere effetto",
			k_bans = "Banditi",
			k_reworks = "Aggiunti/Reimmaginati",
			ml_enemy_loc = { "Posizione", "nemico" },
			ml_mp_kofi_message = {
				"Questa mod e server è",
				"sviluppata e mantenuta da",
				"una persona, se ti è",
				"piaciuta considera",
			},
			ml_lobby_info = { "Info", "Lobby" },
			loc_ready = "Pronto per il PvP",
			loc_selecting = "Selezionando un buio",
			loc_shop = "Facendo acquisti",
			loc_playing = "Giocando ",
		},
		v_dictionary = {
			a_mp_art = { "Disegno: #1#" },
			a_mp_code = { "Codice: #1#" },
			a_mp_idea = { "Idea: #1#" },
			a_mp_skips_ahead = { "#1# Bui Saltati Avanti" },
			a_mp_skips_behind = { "#1# Bui Saltati Indietro" },
			a_mp_skips_tied = { "Uguali" },
			k_banned_objs = "#1# Banditi",
			k_no_banned_objs = "Non Ci Sono #1# Banditi",
			k_reworked_objs = "#1# Aggiunti/Reimmaginati",
			k_no_reworked_objs = "Non Ci Sono #1# Aggiunti/Reimmaginati",
		},
		v_text = {
			ch_c_hanging_chad_rework = { "{C:attention}Scheda non valida{} è {C:dark_edition}reimmaginata" },
			ch_c_glass_cards_rework = { "Le {C:attention}Glass Cards{} sono {C:dark_edition}reimmaginate" },
		},
		challenge_names = {
			c_mp_misprint_deck = "Mazzo con errori di stampa",
			c_mp_legendaries = "Legendari",
			c_mp_psychosis = "Psicosi",
			c_mp_scratch = "Da zero",
			c_mp_twin_towers = "Torri gemelle",
			c_mp_in_the_red = "In rosso",
			c_mp_paper_money = "La radice di ogni male",
			c_mp_high_hand = "Mano alta",
			c_mp_chore_list = "Lista dei lavoretti",
			c_mp_oops_all_jokers = "Oops! Tutti Jolly",
			c_mp_divination = "Divinazione",
			c_mp_skip_off = "Salta tutto",
			c_mp_lets_go_gambling = "Let's go gambling!",
			c_mp_speed = "Velocità",
		},
	},
}
