-- Localization by @koukichi_kkc
-- 気になる点がありましたらサーバー内でもDMでもお気軽にご相談ください!
return {
	descriptions = {
		Joker = {
			j_broken = {
				name = "エラー",
				text = {
					"このカードは現在使用しているMODのバージョンでは未実装、",
					"またはデータが壊れている可能性があります",
				},
			},
			j_mp_defensive_joker = {
				name = "盾役ジョーカー",
				text = {
					"相手より {C:red,E:1}ライフ{} が少ないとき",
					"差1つにつき",
					"チップ {C:chips}+#1#{}",
					"{C:inactive}(現在 チップ {C:chips}+#2#{C:inactive})",
				},
			},
			j_mp_skip_off = {
				name = "おサボり",
				text = {
					"{C:attention}ブラインド{} をスキップした回数が",
					"{X:purple,C:white}相手{} と比べて1つ多くなる毎に",
					"ハンド {C:blue}+#1#{} ディスカード {C:red}+#2#{} ",
					"{C:inactive}(現在 {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive})",
					"{C:inactive}({X:purple,C:white}相手{} {C:inactive}#5#)",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Let’s ギャンブル！",
				text = {
					"{C:green}#2#分の#1#{} の確率で",
					"{X:mult,C:white}X#3#{} と {C:money}$#4#{} 得る",
					"PvPブラインド中では",
					"{C:green}#6#分の#5#{} の確率で",
					"{X:purple,C:white}相手{} が {C:money}$#7#{} 得る",
					"可能性もある",
				},
			},
			j_mp_speedrun = {
				name = "タイムアタック",
				text = {
					"{X:purple,C:white}相手{} より先に {C:attention}PvPブラインド{} に",
					"到達した場合、{C:spectral}スペクトル{}カードを1つ作る",
					"{C:inactive}(空きが必要)",
				},
			},
			j_mp_conjoined_joker = {
				name = "結合双生ジョーカー",
				text = {
					"{C:attention}PvPブラインド{} で",
					"{X:purple,C:white}相手{} の残り{C:blue}ハンド{} 1つにつき",
					"倍率 {X:mult,C:white}X#1#{}",
					"{C:inactive}(最大 倍率 {X:mult,C:white}X#2#{C:inactive})",
					"{C:inactive}(現在 倍率 {X:mult,C:white}X#3#{C:inactive})",
				},
			},
			j_mp_penny_pincher = {
				name = "守銭奴",
				text = {
					"ラウンド終了時",
					"{X:purple,C:white}相手{} が直近のショップで消費したお金",
					"{C:money}$#2#{} ごとに {C:money}$#1#{} 得る",
					"{C:inactive}(現在獲得できる金額 {C:money} $#3# {C:inactive})",
				},
			},
			j_mp_taxes = {
				name = "税務係",
				text = {
					"{X:purple,C:white}相手{} がジョーカーを売るたびに",
					"倍率 {C:mult}+#1#{}",
					"{C:inactive}(現在 {C:mult}+#2#{C:inactive})",
				},
			},
			j_mp_magnet = {
				name = "マグネット",
				text = {
					"{C:attention}#1#{} ラウンド後",
					"このジョーカーを売ると",
					"{X:purple,C:white}相手{} の最も売値が高い {C:attention}ジョーカー{}を {C:attention}複製{} する",
					"{C:inactive}(現在 {C:attention}#2#{C:inactive}/#3#)",
				},
			},
			j_mp_pizza = {
				name = "ピッツァ",
				text = {
					"自分のディスカード{C:red}+#1#{}",
					"{X:purple,C:white}相手{} のディスカード {C:red}+#2#{}",
					"{C:inactive}({C:attention}PvPブラインド{} {C:inactive}終了後に消滅する)"
				},
			},
			j_mp_pacifist = {
				name = "平和主義者",
				text = {
					"{C:attention}PvPブラインドでない{} とき",
					"倍率 {X:mult,C:white}X#1#{}",
				},
			},
			j_mp_hanging_chad = {
				name = "ハンギングチャド",
				text = {
					"プレイしたカードで、",
					"{C:attention}最初{} と {C:attention}2番目{} にスコアされたものを",
					"再発動する",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "小惑星",
				text = {
					"{X:purple,C:white}相手{} の一番高い",
					"{C:legendary,E:1} ポーカーハンド{} のレベルを #1# 下げる",
					"{C:inactive}({C:attention}PvPブラインド開始時{} {C:inactive}に効果が発動する)"
				},
			},
		},
		Blind = {
			bl_mp_nemesis = {
				name = "ライバル",
				text = {
					"スコアの高い方が勝ち！",
					"負けるとライフを1失う",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "ファントム",
				text = {
					"{C:attention}エターナル{} と {C:dark_edition}ネガティブ{} を併せ持つ",
					"作成も破壊も {X:purple,C:white}相手{} にしかできない",
				},
			},
		},
		Enhanced = {
			m_mp_glass = {
				name = "グラスカード",
				text = {
					"倍率 {X:mult,C:white} X#1# {}",
					"ただし、{C:green}#3#分の#2#{} の確率で",
					"破壊されてしまう",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "相手",
				text = {
					"{X:purple,C:white}#1#{}",
					"キミの唯一無二のライバルだ。",
				},
			},
		},
	},
	misc = {
		labels = {
			mp_phantom = "ファントム",
		},
		challenge_names = {
			c_mp_standard = "スタンダード",
			c_mp_badlatro = "Badlatro",
			c_mp_tournament = "トーナメント",
			c_mp_weekly = "ウィークリー",
			c_mp_vanilla = "バニラ",
		},
		dictionary = {
			b_singleplayer = "シングルプレイ",
			b_join_lobby = "ロビーに参加",
			b_return_lobby = "ロビーに戻る",
			b_reconnect = "再接続",
			b_create_lobby = "ロビーの作成",
			b_start_lobby = "このモードで作成",
			b_ready = "準備OK!",
			b_unready = "解除",
			b_leave_lobby = "タイトルへ戻る",
			b_mp_discord = "参加する",
			b_start = "スタート",
			b_wait_for_host_start = { "ゲーム開始を", "待っています" },
			b_wait_for_players = { "参加者を", "待っています" },
			b_lobby_options = "ロビー設定",
			b_copy_clipboard = "クリップボードにコピー",
			b_view_code = "ロビーID",
			b_copy_code = "ロビーIDコピー",
			b_leave = "タイトルへ戻る",
			b_opts_cb_money = "ライフ減少時に$を受け取る",
			b_opts_no_gold_on_loss = "通常ラウンドでノルマ未達の場合にブラインド報酬を受け取らない",
			b_opts_death_on_loss = "通常ラウンドでノルマ未達の場合にライフを1失う",
			b_opts_start_antes = "PvP開始アンティ",
			b_opts_diff_seeds = "お互いに別シードでプレイ",
			b_opts_lives = "ライフ",
			b_opts_multiplayer_jokers = "マルチプレイオリジナルカードを有効",
			b_opts_player_diff_deck = "お互いに別デッキ､別ステークでプレイ",
			b_opts_normal_bosses = "通常のボスブラインドの効果ありでPvPを行う",
			b_opts_timer = "タイマーを使用する",
			b_reset = "リセット",
			b_set_custom_seed = "シード値を指定",
			b_mp_kofi_button = "サポートページへ",
			b_unstuck = "詰み防止処置(β)",
			b_unstuck_blind = "PvPﾌﾞﾗｲﾝﾄﾞに進まなかったとき",
			b_misprint_display = "山札の一番上のカードを表示する",
			b_players = "プレイヤー",
			b_lobby_info = "ロビー情報",
			b_continue_singleplayer = "シングルプレイで再開する",
			b_the_order_integration = "「The Order」MODを有効にする",
			b_view_nemesis_deck = "デッキを見る",
			b_toggle_jokers = "ジョーカー切替",
			k_continue_singleplayer_tooltip = "現在のシングルプレイに保存されているデータは失われます",
			k_enemy_score = "相手のスコア",
			k_enemy_hands = "相手の残りハンド ",
			k_coming_soon = "Coming Soon!",
			k_wait_enemy = "相手のプレイが終わるまでお待ちください...",
			k_wait_enemy_reach_this_blind = "相手の結果をお待ちください...",
			k_lives = "ライフ",
			k_lost_life = "ライフ減少",
			k_total_lives_lost = " 失ったライフ数 (1つにつき$4)",
			k_attrition_name = "消耗戦",
			k_enter_lobby_code = "ロビーIDを入力",
			k_paste = "クリップボードからペースト",
			k_username = "ユーザーネーム",
			k_enter_username = "ニックネームを入力",
			k_join_discord = "Balatro Multiplayer Discordサーバー",
			k_discord_msg = "MODについての最新情報をお届け中！",
			k_enter_to_save = "Enterで保存",
			k_in_lobby = "ロビー内",
			k_connected = "マルチプレイサービス接続中",
			k_warn_service = "マルチプレイサービスが見つかりません",
			k_set_name = "メインメニューからユーザーネームを設定できます (Mods > Multiplayer > Config)",
			k_mod_hash_warning = "古いバージョンを利用しているユーザーがいるため、不具合が発生する可能性があります",
			k_warning_unlock_profile = "現在使用しているプロフィールは、全コレクションがアンロックされていません。新しいプロフィールを作成し、プロフィール設定ですべてのアンロックを解除したデータを使用してください。",
			k_warning_nemesis_unlock = "あなたの対戦相手は、全コレクションがアンロックされていないプロフィールで参加しています。新しいプロフィールを作成し、プロフィールの設定ですべてのアンロックを解除するよう指示してください。",
			k_warning_no_order = "参加者の全員が「The Order MOD」を有効、または無効にしていません。このままスタートすると、お互いが別のシードでプレイすることになります。",
			k_warning_cheating = "これが表示される場合、対戦相手が不正を行っている可能性があります。ランク戦であれば、Discordサーバーにて「%s」というメッセージを送り、supportチャンネルでサポートチケットを開いて報告してください。",
			k_message1 = "Hold on, my mom made pizza pops",
			k_message2 = "One sec, i gotta grab my slow cooker pork roast",
			k_message3 = "One moment, getting a call from my mom",
			k_message4 = "Brb, my cat is on fire",
			k_message5 = "Wait, I think I left the stove on",
			k_message6 = "Hold up, my pet rock just ran away",
			k_message7 = "One sec, my plants are asking for water",
			k_message8 = "Brb, my socks are plotting against me",
			k_message9 = "Sorry, my WiFi is having an existential crisis",
			k_lobby_options = "ロビー設定",
			k_connect_player = "参加者一覧",
			k_opts_only_host = "設定を変更できるのはホストのみです",
			k_opts_gm = "詳細設定",
			k_opts_pvp_start_round = "PvP初戦アンティ",
			k_opts_pvp_timer = "タイマーの秒数",
			k_opts_showdown_starting_antes = "PvP初戦アンティ(バーサスルール限定)",
			k_opts_pvp_timer_increment = "ブラインドスキップ時のタイマー追加秒数",
			k_bl_life = "Life",
			k_bl_or = "or",
			k_bl_death = "Death",
			k_bl_mostchips = "(PvPブラインド)",
			k_current_seed = "シード値: ",
			k_random = "ランダム",
			k_standard = "スタンダード",
			k_standard_description = "マルチプレイオリジナルカードやPvPブラインドが追加された標準的なルール",
			k_vanilla = "バニラ",
			k_vanilla_description = "マルチプレイオリジナルカードやカードの修正なしのルール。",
			k_weekly = "ウィークリー",
			k_weekly_description = "(ほぼ)毎週変わる特別なルール 何かは見てからのお楽しみ！",
			k_tournament = "トーナメント",
			k_tournament_description = "スタンダードと内容は同じですが、ロビー設定の変更が出来ません",
			k_badlatro = "Badlatro",
			k_badlatro_description = "DiscordサーバーでDr.Monty(@dr_monty_the_snek)さんが作成したルール",
			k_attrition = "消耗戦",
			k_attrition_description = "アンティ2以降のボスブラインドがPvPブラインドになっている状態で戦うモード。\n事前にしっかりと準備をしてから対戦に挑めるぞ。",
			k_showdown = "バーサス",
			k_showdown_description = "アンティ2のボスブラインド以降の全てのブラインドがPvPブラインドになっている状態で戦うモード。\n常に対戦相手との連戦になるぞ。",
			k_survival = "サバイバル",
			k_survival_description = "PvPブラインドが登場しないモード。\n通常のBalatroと同じルールで、相手がゲームオーバーになったブラインドより先に進めた方の勝ち。",
			k_oops_ex = "ハズレ！",
			k_asteroids = "小惑星",
			k_amount_short = "金額",
			k_filed_ex = "提出!",
			k_timer = "タイマー",
			k_mods_list = "使用しているMOD",
			k_enemy_jokers = "相手のジョーカー",
			k_your_jokers = "自分のジョーカー",
			k_nemesis_deck = "相手のデッキ",
			k_your_deck = "自分のデッキ",
			k_the_order_credit = "制作者 @MathIsFun_",
			k_the_order_integration_desc = "これにより、ショップに並ぶカードの内部テーブルがアンティごとに変更ではなく、常に1つの内部テーブルだけを使用するMODが適用されます",
			k_requires_restart = "有効にするには再起動が必要です",
			k_bans = "出現しないアイテム",
			k_reworks = "追加､修正されたアイテム",
			ml_enemy_loc = { "相手の", "プレイ状況" },
			ml_mp_kofi_message = {
				"このMODは個人製作で成り立っています。",
				"気に入っていただけた方は、",
				"こちらからサポートを",
				"よろしくお願いします！",
			},
			ml_lobby_info = { "ロビー", "情報" },
			loc_ready = "準備OK！",
			loc_selecting = "ブラインド選択",
			loc_shop = "ショップ",
			loc_playing = "",
		},
		v_dictionary = {
			a_mp_art = { "イラスト #1#" },
			a_mp_code = { "制作 #1#" },
			a_mp_idea = { "考案 #1#" },
			a_mp_skips_ahead = { "より#1#回多い" },
			a_mp_skips_behind = { "より#1#回少ない" },
			a_mp_skips_tied = { "と同数" },
			k_banned_objs = "出現しない#1#",
			k_no_banned_objs = "出現しない#1#はありません",
			k_reworked_objs = "追加､修正された#1#",
			k_no_reworked_objs = "追加､修正された#1#はありません",
		},
		v_text = {
			ch_c_hanging_chad_rework = { "{C:attention}ハンギングチャド{}は{C:dark_edition}マルチ用に改良されています。" },
			ch_c_glass_cards_rework = { "{C:attention}グラスカード{}は{C:dark_edition}マルチ用に改良されています。" },
		},
		challenge_names = {
			c_mp_misprint_deck = "バグシードデッキ",
			c_mp_legendaries = "レジェンドたち",
			c_mp_psychosis = "精神病",
			c_mp_scratch = "1から作ろう",
			c_mp_twin_towers = "2本の柱",
			c_mp_in_the_red = "赤字経営",
			c_mp_paper_money = "お札",
			c_mp_high_hand = "1度きり",
			c_mp_chore_list = "チェックリスト",
			c_mp_oops_all_jokers = "ぜんぶジョーカーだ！",
			c_mp_divination = "まやかし占い師",
			c_mp_skip_off = "おサボり",
			c_mp_lets_go_gambling = "Let's ギャンブル！",
			c_mp_speed = "タイムアタック",
		},
	},
}
