-- Localization by @blablabla_c and @koenveck on discord
return {
	descriptions = {
		Joker = {
			j_broken = {
				name = "KAPOT",
				text = {
					"Deze kaart is kapot of",
					"niet geïmplementeerd in de huidige versie",
					"van een mod die je gebruikt.",
				},
			},
			j_mp_defensive_joker = {
				name = "Verdedigende Joker",
				text = {
					"{C:chips}+#1#{} fiches voor elk {C:red,E:1}leven{}",
					"minder dan je {X:purple,C:white}Aartsvijand{}",
					"{C:inactive}(Momenteel {C:chips}+#2#{C:inactive} fiches)",
				},
			},
			j_mp_skip_off = {
				name = "Over-Slag",
				text = {
					"{C:blue}+#1#{} Handen en {C:red}+#2#{} weggooimogelijkheden",
					"per {C:attention}Blind{} die je meer hebt overgeslagen",
					"dan jouw {X:purple,C:white}Aartsvijand{}",
					"{C:inactive}(Momenteel {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive}, #5#)",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Let's Go Gambling",
				text = {
					"{C:green}#1# in #2#{} kans om",
					"{X:mult,C:white}X#3#{} Multi en {C:money}$#4#{}",
					"{C:green}#5# in #6#{} kans om",
					"je {X:purple,C:white}Aartsvijand{} {C:money}$#7#{} te geven",
				},
			},
			j_mp_speedrun = {
				name = "SPEEDRUN",
				text = {
					"Als je een {C:attention}PvP Blind",
					"bereikt voor je {X:purple,C:white}Aartsvijand{},",
					"creëer een willekeurige {C:spectral}Spectrale{} kaart",
					"{C:inactive}(Moet ruimte voor zijn)",
				},
			},
			j_mp_conjoined_joker = {
				name = "Siamese Joker",
				text = {
					"Tijdens een {C:attention}PvP Blind{}, krijg",
					"{X:mult,C:white}X#1#{} Multi voor elke {C:blue}Hand{}",
					"die je {X:purple,C:white}Aartsvijand{} nog over heeft",
					"{C:inactive}(Maximum {X:mult,C:white}X#2#{C:inactive} Multi, Momenteel {X:mult,C:white}X#3#{C:inactive} Multi)",
				},
			},
			j_mp_penny_pincher = {
				name = "Geldwolf",
				text = {
					"Aan het begin van de winkel, krijg",
					"{C:money}$#1#{} voor elke {C:money}$#2#{}",
					"die je {X:purple,C:white}Aartsvijand{} in de vorige winkel heeft gespendeerd",
				},
			},
			j_mp_taxes = {
				name = "Belasting",
				text = {
					"Wanneer je {X:purple,C:white}Aartsvijand'{} een kaart",
					"verkoopt, krijg {C:mult}+#1#{} Multi",
					"{C:inactive}(Momenteel {C:mult}+#2#{C:inactive} Multi)",
				},
			},
			j_mp_magnet = {
				name = "Magneet",
				text = {
					"Na {C:attention}#1#{} ronde,",
					"verkoop deze kaart om je {X:purple,C:white}Aartsvijands{}",
					"{C:attention}Joker{} met hoogste verkoopwaarde",
					"te {C:attention}kopiëren{}",
					"{C:inactive}(Momenteel {C:attention}#2#{C:inactive}/#3# rondes)",
					"{C:inactive,s:0.8}(Kan Joker state niet kopiëren)",
				},
			},
			j_mp_pizza = {
				name = "Pizza",
				text = {
					"{C:red}+#1#{} weggooimogelijkheden voor alle spelers",
					"{C:red}-#2#{} weggooimogelijkheden wanneer een speler",
					"een blind selecteert",
					"Opgegeten wanneer je {X:purple,C:white}Aartsvijand{} overslaat",
				},
			},
			j_mp_pacifist = {
				name = "Pacifist",
				text = {
					"{X:mult,C:white}X#1#{} Multi wanneer",
					"je niet in een {C:attention}PvP Blind{} bent",
				},
			},
			j_mp_hanging_chad = {
				name = "Ongeldige Stem",
				text = {
					"Reactiveer de {C:attention}eerste{} en {C:attention}tweede{}",
					"gespeelde kaart die scoort",
					"{C:attention}#1#{} keer extra",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Asteroïde",
				text = {
					"Verwijder #1# level van",
					"je {X:purple,C:white}Aartsvijands'{}",
					"hoogste level",
					"{C:legendary,E:1}poker hand{}",
				},
			},
		},
		Blind = {
			bl_mp_nemesis = {
				name = "Je Aartsvijand",
				text = {
					"Neem het op tegen een andere speler,",
					"meeste fiches wint",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "Spook",
				text = {
					"{C:attention}Eeuwig{} en {C:dark_edition}Negatief{}",
					"Gecreëerd en vernietigd door je {X:purple,C:white}Aartsvijand{}",
				},
			},
		},
		Enhanced = {
			m_mp_glass = {
				name = "Glazen Kaart",
				text = {
					"{X:mult,C:white} X#1# {} Multi",
					"{C:green}#2# in #3#{} kans om",
					"kaart te vernietigen",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Aartsvijand",
				text = {
					"{X:purple,C:white}#1#{}",
					"Je enige echte Aartsvijand",
				},
			},
		},
	},
	misc = {
		labels = {
			mp_phantom = "Spook",
		},
		challenge_names = {
			c_mp_standard = "Standaard",
			c_mp_badlatro = "Badlatro",
			c_mp_tournament = "Tournament",
			c_mp_weekly = "Weekelijks",
			c_mp_vanilla = "Vanilla",
		},
		dictionary = {
			b_singleplayer = "Singleplayer",
			b_join_lobby = "Sluit je aan bij een lobby",
			b_return_lobby = "Ga terug naar lobby",
			b_reconnect = "Opnieuw verbinding maken",
			b_create_lobby = "Creëer Lobby",
			b_start_lobby = "Start Lobby",
			b_ready = "Klaar",
			b_unready = "Niet meer klaar",
			b_leave_lobby = "Verlaat de lobby",
			b_mp_discord = "Balatro Multiplayer Discord Server",
			b_start = "START",
			b_wait_for_host_start = { "WACHTEN OP", "HOST OM TE STARTEN" },
			b_wait_for_players = { "WACHTEN OP", "SPELERS" },
			b_lobby_options = "LOBBY OPTIES",
			b_copy_clipboard = "Kopieer naar klembord",
			b_view_code = "BEKIJK CODE",
			b_leave = "VERLAAT",
			b_opts_cb_money = "Geef comeback $ bij levensverlies",
			b_opts_no_gold_on_loss = "Krijg geen blind beloning na verlies van ronde",
			b_opts_death_on_loss = "Verlies een leven op non-PvP ronde verlies",
			b_opts_start_antes = "Beginnende Antes",
			b_opts_diff_seeds = "Spelers hebben verschillende seeds",
			b_opts_lives = "Levens",
			b_opts_multiplayer_jokers = "Schakel Multiplayer kaarten in",
			b_opts_player_diff_deck = "Spelers hebben verschillende Kaartspellen",
			b_reset = "Reset",
			b_set_custom_seed = "Stel Aangepaste Seed In",
			b_mp_kofi_button = "mij te steunen op Ko-Fi",
			b_unstuck = "Kom los",
			b_unstuck_arcana = "Vast in een Boosterpakket",
			b_unstuck_blind = "Stuck buiten PvP",
			k_enemy_score = "Huidige score van je vijand",
			k_enemy_hands = "Handen van vijand over: ",
			k_coming_soon = "Binnenkort Beschikbaar!",
			k_wait_enemy = "Wachten tot vijand is geëindigt...",
			k_lives = "Levens",
			k_lost_life = "Leven verloren",
			k_total_lives_lost = " Aantal Levens Verloren ($4 per stuk)",
			k_attrition_name = "Standaard",
			k_enter_lobby_code = "Voer de Lobby Code in",
			k_paste = "Plak Van Klembord",
			k_username = "Gebruikersnaam:",
			k_enter_username = "Voer gebruikersnaam in",
			k_join_discord = "Join de ",
			k_discord_msg = "Je kan daar eventuele bugs melden en kan er spelers vinden om tegen te spelen",
			k_enter_to_save = "Druk op enter om op te slaan",
			k_in_lobby = "In de lobby",
			k_connected = "Verbonden met Service",
			k_warn_service = "WAARSCHUWING: Kan de multiplayer service niet vinden",
			k_set_name = "Verander je gebruikersnaam in het hoofdmenu! (Mods > Multiplayer > Config)",
			k_mod_hash_warning = "Spelers hebben verschillende mods of mod versies! Dit kan problemen veroorzaken! Players have different mods or mod versions! This can cause problems!",
			k_lobby_options = "Lobby Opties",
			k_connect_player = "Verbonden Spelers:",
			k_opts_only_host = "Enkel de Lobby Host kan deze opties veranderen",
			k_opts_gm = "Spelmodus Modificaties",
			k_bl_life = "Leven",
			k_bl_or = "of",
			k_bl_death = "Dood",
			k_current_seed = "Huidige seed: ",
			k_random = "Willekeurig",
			k_standard = "Standaard",
			k_standard_description = "De standaard regels, inclusief Multiplayer kaarten en veranderingen aan Balatro zelf om beter te passen binnen Multiplayer.",
			k_vanilla = "Vanilla",
			k_vanilla_description = "De vanilla regels, geen Multiplayer kaarten, geen veranderingen aan Balatro zelf.",
			k_weekly = "wekelijks",
			k_weekly_description = "Speciale regels die wekelijks of om de week veranderen. Je moet zelf maar uitzoeken wat het deze week doet! Momenteel: ",
			k_tournament = "Tournament",
			k_tournament_description = "De tournament regels, dit doet hetzelfde als de standaard regels maar de instellingen kunnen niet worden gewijzigd.",
			k_badlatro = "Badlatro",
			k_badlatro_description = "Origineel wekelijkse regels bedacht door @dr_monty_the_snek in de discord server die permanent aan de mod zijn toegevoegd.",
			k_oops_ex = "Oeps!",
			ml_enemy_loc = { "Vijand", "locatie" },
			ml_mp_kofi_message = {
				"Deze mod en server zijn volledig",
				"gemaakt en onderhouden door ",
				"één persoon, als je het leuk vindt",
				"denk erover na om",
			},
			loc_ready = "Klaar voor PvP",
			loc_selecting = "Blind aan het kiezen",
			loc_shop = "Shoppen",
			loc_playing = "Speelt ",
		},
		v_dictionary = {
			a_mp_art = { "Kunst: #1#" },
			a_mp_code = { "Code: #1#" },
			a_mp_idea = { "Idee: #1#" },
			a_mp_skips_ahead = { "#1# Overslagen Meer" },
			a_mp_skips_behind = { "#1# Overslagen Minder" },
			a_mp_skips_tied = { "Gelijk" },
		},
		v_text = {
			ch_c_hanging_chad_rework = { "{C:attention}Ongeldige stem{} is {C:dark_edition}verandert" },
			ch_c_glass_cards_rework = { "{C:attention}Glazen kaarten{} zijn {C:dark_edition}verandert" },
		},
	},
}
